# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance_callback', '0002_auto_20170328_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_levels',
            name='level',
            field=models.IntegerField(),
        ),
    ]
