# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance_callback', '0003_auto_20170328_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microfinance',
            name='reg_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
