# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance_callback', '0004_auto_20170328_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=25)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='session_levels',
            name='id',
        ),
        migrations.AlterField(
            model_name='session_levels',
            name='session_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
